'use client'
import { FormEvent, useState } from 'react'
import { QRCodeSVG } from 'qrcode.react'

type Data = { totalClicks:number; daily:Record<string,number>; countries:Record<string,number>; devices:Record<string,number>; browsers:Record<string,number>; referrers:Record<string,number>; recent:any[]; link:{slug:string;original_url:string} }
const pairs = (x: Record<string, number>) => Object.entries(x).sort((a,b) => b[1]-a[1])

export default function Home() {
  const [url,setUrl]=useState(''),[slug,setSlug]=useState(''),[shortUrl,setShortUrl]=useState(''),[error,setError]=useState(''),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(false)
  async function shorten(e:FormEvent) { e.preventDefault(); setLoading(true); setError(''); setData(null); try { const r=await fetch('/api/shorten',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({originalUrl:url,customSlug:slug})}); const j=await r.json(); if(!r.ok) throw Error(j.error); setShortUrl(j.shortUrl); setUrl(''); setSlug('') } catch(e:any) { setError(e.message) } finally { setLoading(false) } }
  async function analytics(value:string) { setError(''); const s=value.split('/').pop(); const r=await fetch('/api/analytics/'+s); const j=await r.json(); if(!r.ok) return setError(j.error); setData(j) }
  const max=data?Math.max(1,...Object.values(data.daily)):1
  return <main className="container"><h1>ProtonVPN URL Shortener</h1><p className="muted">URL pendek dengan QR code dan statistik klik.</p><section className="card"><form onSubmit={shorten}><div className="row"><input className="field" type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://contoh.com/url-panjang"/><input className="field" value={slug} onChange={e=>setSlug(e.target.value)} placeholder="custom-alias (opsional)"/><button disabled={loading}>{loading?'Membuat...':'Buat link'}</button></div></form>{error&&<p className="error">{error}</p>}{shortUrl&&<div className="success"><b>Link berhasil dibuat:</b><br/><a href={shortUrl} target="_blank">{shortUrl}</a><div className="row" style={{marginTop:12}}><button className="secondary" onClick={()=>navigator.clipboard.writeText(shortUrl)}>Salin</button><button className="secondary" onClick={()=>analytics(shortUrl)}>Lihat analitik</button></div><div style={{marginTop:16}}><QRCodeSVG value={shortUrl} size={150}/></div></div>}</section><section className="card"><h2>Analitik link</h2><div className="row"><input className="field" placeholder="Masukkan short URL atau slug" onKeyDown={e=>{if(e.key==='Enter')analytics((e.target as HTMLInputElement).value)}}/><button onClick={e=>{const input=(e.currentTarget.previousSibling as HTMLInputElement);analytics(input.value)}}>Cek statistik</button></div>{data&&<><p className="muted" style={{wordBreak:'break-all',marginTop:16}}>{data.link.original_url}</p><div className="stats" style={{marginTop:16}}><div className="stat"><b>{data.totalClicks}</b>Total klik</div><div className="stat"><b>{pairs(data.countries).length}</b>Negara</div><div className="stat"><b>{pairs(data.devices).map(x=>x[0]).join(', ')||'-'}</b>Device</div></div><h3>Klik harian</h3><div className="chart">{pairs(data.daily).sort().slice(-14).map(([d,n])=><div className="bar" title={`${d}: ${n}`} style={{height:`${Math.max(24,n/max*150)}px`}} key={d}>{n}</div>)}</div><h3>Negara</h3><p>{pairs(data.countries).map(([k,v])=>`${k}: ${v}`).join(' · ')||'Belum ada klik'}</p><h3>Klik terbaru</h3><table className="table"><thead><tr><th>Waktu</th><th>Negara</th><th>Kota</th><th>Device</th><th>Browser</th></tr></thead><tbody>{data.recent.map((x:any)=><tr key={x.id}><td>{new Date(x.clicked_at).toLocaleString('id-ID')}</td><td>{x.country}</td><td>{x.city}</td><td>{x.device}</td><td>{x.browser}</td></tr>)}</tbody></table></>}</section></main>
}
